use crate::model::Report;
use anyhow::{Context, Result};
use std::path::Path;

pub async fn write_all(out_dir: &Path, report: &Report) -> Result<()> {
    tokio::fs::create_dir_all(out_dir).await?;
    write_json(out_dir, report).await?;
    write_markdown(out_dir, report).await?;
    write_prompts(out_dir, report).await?;
    write_rust_module(out_dir, report).await?;
    Ok(())
}

async fn write_json(out_dir: &Path, report: &Report) -> Result<()> {
    let path = out_dir.join("papers.json");
    let json = serde_json::to_string_pretty(report)?;
    tokio::fs::write(&path, json).await.with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

async fn write_markdown(out_dir: &Path, report: &Report) -> Result<()> {
    let path = out_dir.join("papers.md");
    let mut s = String::new();
    s.push_str(&format!(
        "# Hugging Face Daily Papers — {}\n\n",
        report.target_date
    ));
    s.push_str(&format!(
        "_Generated at {} · {} papers_\n\n",
        report.generated_at, report.total
    ));
    s.push_str("| # | Paper | arXiv | HF |\n|---:|---|---|---|\n");
    for (i, p) in report.papers.iter().enumerate() {
        s.push_str(&format!(
            "| {n} | **{title}** | [{id}]({abs}) | [link]({hf}) |\n",
            n = i + 1,
            title = md_escape(&p.title),
            id = p.id,
            abs = p.sources.arxiv_abs,
            hf = p.sources.huggingface,
        ));
    }
    s.push_str("\n---\n\n");
    for p in &report.papers {
        s.push_str(&format!("## {}\n\n", p.title));
        s.push_str(&format!(
            "- arXiv: <{}>\n- PDF: <{}>\n- HF: <{}>\n",
            p.sources.arxiv_abs, p.sources.arxiv_pdf, p.sources.huggingface
        ));
        if !p.keywords.is_empty() {
            s.push_str(&format!("- Keywords: {}\n", p.keywords.join(", ")));
        }
        s.push_str("\n<details><summary>AI-ready prompt</summary>\n\n```text\n");
        s.push_str(&p.prompt);
        s.push_str("\n```\n\n</details>\n\n");
    }
    tokio::fs::write(&path, s).await.with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

async fn write_prompts(out_dir: &Path, report: &Report) -> Result<()> {
    let prompt_dir = out_dir.join("prompts");
    tokio::fs::create_dir_all(&prompt_dir).await?;
    for p in &report.papers {
        let path = prompt_dir.join(format!("{}.txt", p.id));
        tokio::fs::write(&path, &p.prompt).await?;
    }
    Ok(())
}

async fn write_rust_module(out_dir: &Path, report: &Report) -> Result<()> {
    let path = out_dir.join("papers.rs");
    let mut s = String::new();
    s.push_str("// Auto-generated by hf-paper-lens. Do not edit by hand.\n");
    s.push_str("// Each entry is an AI-ready prompt bundle for one paper.\n\n");
    s.push_str("pub struct Paper {\n");
    s.push_str("    pub id: &'static str,\n");
    s.push_str("    pub title: &'static str,\n");
    s.push_str("    pub hf_url: &'static str,\n");
    s.push_str("    pub arxiv_abs: &'static str,\n");
    s.push_str("    pub arxiv_pdf: &'static str,\n");
    s.push_str("    pub keywords: &'static [&'static str],\n");
    s.push_str("    pub prompt: &'static str,\n");
    s.push_str("}\n\n");
    s.push_str(&format!(
        "pub const GENERATED_AT: &str = {gen:?};\npub const TARGET_DATE: &str = {date:?};\n\n",
        gen = report.generated_at,
        date = report.target_date
    ));
    s.push_str(&format!(
        "pub const PAPERS: &[Paper] = &[\n"
    ));
    for p in &report.papers {
        s.push_str("    Paper {\n");
        s.push_str(&format!("        id: {:?},\n", p.id));
        s.push_str(&format!("        title: {:?},\n", p.title));
        s.push_str(&format!("        hf_url: {:?},\n", p.sources.huggingface));
        s.push_str(&format!("        arxiv_abs: {:?},\n", p.sources.arxiv_abs));
        s.push_str(&format!("        arxiv_pdf: {:?},\n", p.sources.arxiv_pdf));
        s.push_str("        keywords: &[");
        for (i, k) in p.keywords.iter().enumerate() {
            if i > 0 {
                s.push_str(", ");
            }
            s.push_str(&format!("{:?}", k));
        }
        s.push_str("],\n");
        s.push_str(&format!("        prompt: {:?},\n", p.prompt));
        s.push_str("    },\n");
    }
    s.push_str("];\n");
    tokio::fs::write(&path, s).await.with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn md_escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}
